// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function GetConfig():Promise<entity.Result>;

export function ResetConfig():Promise<entity.Result>;

export function SaveConfig(arg1:entity.Config):Promise<entity.Result>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
