// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {utils} from '../models';

export function GetWebSocketPort():Promise<number>;

export function SaveConnection(arg1:entity.SSHConfig):Promise<utils.Result>;

export function ServerConnection(arg1:entity.SSHConfig):Promise<utils.Result>;

export function TestConnection(arg1:entity.SSHConfig):Promise<utils.Result>;
