// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWebSocketPort() {
  return window['go']['service']['Connection']['GetWebSocketPort']();
}

export function SaveConnection(arg1) {
  return window['go']['service']['Connection']['SaveConnection'](arg1);
}

export function ServerConnection(arg1) {
  return window['go']['service']['Connection']['ServerConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['service']['Connection']['TestConnection'](arg1);
}
