// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {utils} from '../models';

export function CreateConnection(arg1:service.SSHConnection):Promise<utils.Result>;

export function ExecCommand(arg1:string):Promise<utils.Result>;
