// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['service']['Connection']['CreateConnection'](arg1);
}

export function ExecCommand(arg1) {
  return window['go']['service']['Connection']['ExecCommand'](arg1);
}
