// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['service']['Connection']['CreateConnection'](arg1);
}

export function GetPrompt() {
  return window['go']['service']['Connection']['GetPrompt']();
}

export function SaveConnection(arg1) {
  return window['go']['service']['Connection']['SaveConnection'](arg1);
}
