// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function ClearLogInfo():Promise<entity.Result>;

export function GetLogInfoList(arg1:string):Promise<entity.Result>;

export function SaveLogInfo(arg1:entity.LogInfo):Promise<entity.Result>;

export function SearchLogInfo(arg1:string,arg2:string):Promise<entity.Result>;
