// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogInfoList(arg1) {
  return window['go']['service']['LogInfo']['GetLogInfoList'](arg1);
}

export function SaveLogInfo(arg1) {
  return window['go']['service']['LogInfo']['SaveLogInfo'](arg1);
}
