// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Shutdown() {
  return window['go']['service']['Project']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['service']['Project']['Startup'](arg1);
}
