// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Shutdown(arg1) {
  return window['go']['service']['Project']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['service']['Project']['Startup'](arg1);
}
